---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: app-admin
    app: app-admin
    verison: v1
  name: app-admin
  namespace: spring-blade
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: app-admin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2023-06-29T16:35:36+08:00'
        sidecar.istio.io/inject: 'true'
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: app-admin
        app: app-admin
        verison: v1
    spec:
      containers:
        imagePullSecrets:
          - name: sanywind
        - image: 'harbor.sanywind.net/cloud/wukong_dev/app-admin:1.0'
          imagePullPolicy: Always
          name: app-admin
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
